# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410f15f51fb8669331c4c1c3f809d61bcdf1d9d3a2f5c2f349fa4674cac29cf6b63d7173a5e0a2c2b16801fb244f22ba99cf76e4fddce7e278a80efeb7fc699f

test:
  secret_key_base: d1eba19f30b0633507efd62bdacd818ed710c422338bd8f143c7aef44cddd80d0bf6d9f07232ff331a1c6f67b03b8fbc423f78acfc1086cb4a380af94e14b8c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
